"""add description col to permission and role

Revision ID: aa90557ef712
Revises: 3be03348cbd4
Create Date: 2026-06-17 11:46:37.274806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa90557ef712'
down_revision: Union[str, Sequence[str], None] = '3be03348cbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('descpription', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('descpription', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'descpription')
    op.drop_column('permissions', 'descpription')
    # ### end Alembic commands ###
