"""normalize user tables

Revision ID: e73c215d7221
Revises: d9a7c3f2b6e1
Create Date: 2026-06-22 11:45:27.978571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e73c215d7221'
down_revision: Union[str, Sequence[str], None] = 'd9a7c3f2b6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('line3', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_addresses_country', 'user_addresses', ['country'], unique=False)
    op.create_index('ix_user_addresses_is_default', 'user_addresses', ['is_default'], unique=False)
    op.create_index('ix_user_addresses_label', 'user_addresses', ['label'], unique=False)
    op.create_index('ix_user_addresses_user_id', 'user_addresses', ['user_id'], unique=False)
    op.create_table('user_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_contacts_is_primary', 'user_contacts', ['is_primary'], unique=False)
    op.create_index('ix_user_contacts_type', 'user_contacts', ['contact_type'], unique=False)
    op.create_index('ix_user_contacts_user_id', 'user_contacts', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_security',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('two_factor_backup_codes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_security_locked_until', 'user_security', ['locked_until'], unique=False)
    op.create_index('ix_user_security_two_factor_enabled', 'user_security', ['two_factor_enabled'], unique=False)
    op.create_index('ix_user_security_user_id', 'user_security', ['user_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_device_info', 'user_sessions', ['device_info'], unique=False)
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_is_revoked', 'user_sessions', ['is_revoked'], unique=False)
    op.create_index('ix_user_sessions_token_hash', 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_settings_preferences', 'user_settings', ['preferences'], unique=False, postgresql_using='gin')
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=True)
    op.create_table('user_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_verifications_channel', 'user_verifications', ['channel'], unique=False)
    op.create_index('ix_user_verifications_is_verified', 'user_verifications', ['is_verified'], unique=False)
    op.create_index('ix_user_verifications_token', 'user_verifications', ['verification_token'], unique=False)
    op.create_index('ix_user_verifications_user_id', 'user_verifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.create_unique_constraint(None, 'authorization_resources', ['key'])
    op.alter_column('permissions', 'resource_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'permissions', ['key'])
    op.drop_constraint(op.f('fk_permissions_resource_id_authorization_resources'), 'permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_constraint(op.f('todos_user_id_fkey'), 'todos', type_='foreignkey')
    op.drop_constraint(op.f('user_has_roles_user_id_fkey'), 'user_has_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_has_roles_role_id_fkey'), 'user_has_roles', type_='foreignkey')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('ix_users_auth_provider', 'users', ['auth_provider'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'password')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_auth_provider', table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('users', 'status')
    op.drop_column('users', 'external_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    op.create_foreign_key(op.f('user_has_roles_role_id_fkey'), 'user_has_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('user_has_roles_user_id_fkey'), 'user_has_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('todos_user_id_fkey'), 'todos', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(op.f('fk_permissions_resource_id_authorization_resources'), 'permissions', 'authorization_resources', ['resource_id'], ['id'])
    op.drop_constraint(None, 'permissions', type_='unique')
    op.alter_column('permissions', 'resource_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'authorization_resources', type_='unique')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_index('ix_user_verifications_user_id', table_name='user_verifications')
    op.drop_index('ix_user_verifications_token', table_name='user_verifications')
    op.drop_index('ix_user_verifications_is_verified', table_name='user_verifications')
    op.drop_index('ix_user_verifications_channel', table_name='user_verifications')
    op.drop_table('user_verifications')
    op.drop_index('ix_user_settings_user_id', table_name='user_settings')
    op.drop_index('ix_user_settings_preferences', table_name='user_settings', postgresql_using='gin')
    op.drop_table('user_settings')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_token_hash', table_name='user_sessions')
    op.drop_index('ix_user_sessions_is_revoked', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_index('ix_user_sessions_device_info', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_security_user_id', table_name='user_security')
    op.drop_index('ix_user_security_two_factor_enabled', table_name='user_security')
    op.drop_index('ix_user_security_locked_until', table_name='user_security')
    op.drop_table('user_security')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_user_contacts_user_id', table_name='user_contacts')
    op.drop_index('ix_user_contacts_type', table_name='user_contacts')
    op.drop_index('ix_user_contacts_is_primary', table_name='user_contacts')
    op.drop_table('user_contacts')
    op.drop_index('ix_user_addresses_user_id', table_name='user_addresses')
    op.drop_index('ix_user_addresses_label', table_name='user_addresses')
    op.drop_index('ix_user_addresses_is_default', table_name='user_addresses')
    op.drop_index('ix_user_addresses_country', table_name='user_addresses')
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
